#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Aug 01, 2026 09:18:45 AM CEST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Lokbox:
    def __init__(self, top=None, rx=0, ry=0, rheight = 1, rwidth=1, name=""):
        #containing frame
        self.Frame = tk.LabelFrame(top)
        self.Frame.place(relx=rx, rely=ry, relheight=rheight, relwidth=rwidth)
        self.Frame.configure(relief='groove')
        self.Frame.configure(text=name)

        #possibly a picture :3
        self.Bild = tk.Canvas(self.Frame)
        self.Bild.place(relx=0.015, rely=0.01, relheight=0.5, relwidth=0.3, bordermode='ignore')
        self.Bild.configure(borderwidth="2")
        self.Bild.configure(relief="ridge")
        self.Bild.configure(selectbackground="#d9d9d9")

        self.Slider = tk.Scale(self.Frame, from_=0.0, to=100.0, resolution=1.0)
        self.Slider.place(relx=0.015, rely=0.67, relheight=0.3, relwidth=0.95)
        self.Slider.configure(activebackground="#d9d9d9")
        self.Slider.configure(length="564")
        self.Slider.configure(orient="horizontal")
        self.Slider.configure(troughcolor="#c4c4c4")

        self.Stop = tk.Button(self.Frame)
        self.Stop.place(relx=0.35, rely=0.01, height=30, width=30, bordermode='ignore')
        self.Stop.configure(activebackground="#d9d9d9")
        self.Stop.configure(compound='left')
        self.Stop.configure(text='''X''')

        self.F1 = tk.Button(self.Frame)
        self.F1.place(relx=0.4, rely=0.01, height=30, width=30, bordermode='ignore')
        self.F1.configure(activebackground="#d9d9d9")
        self.F1.configure(compound='left')
        self.F1.configure(text='''F1''')

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top = tk.Tk()
        top.geometry("800x600+383+94")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("Toplevel 0")

        self.top = top

        self.z21status = tk.Listbox(self.top)
        self.z21status.place(relx=0.806, rely=0.008, relheight=0.983
                , relwidth=0.188)
        self.z21status.configure(background="white")
        self.z21status.configure(exportselection="0")
        self.z21status.configure(font="TkFixedFont")
        self.z21status.configure(selectbackground="#d9d9d9")
        self.z21status.configure(state='disabled')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.Pane = ttk.Panedwindow(self.top, orient="horizontal")
        self.Pane.place(relx=0.005, rely=0.005, relheight=0.9, relwidth=0.775)

        self.lbox = Lokbox(self.Pane, rheight=0.5, name="Lok1")

        self.lbox2 = Lokbox(self.Pane, ry=0.5, rheight=0.5, name="Lok2")

        self.lbox3 = Lokbox(self.Pane, ry=1, rheight=1, name="Lok3")


if __name__ == '__main__':
    root = Toplevel1()
    Toplevel1.loop()




