#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Aug 01, 2026 09:18:45 AM CEST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Relative
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -menu $top.m51 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 800x600+383+94
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    listbox "$top.lis49" \
        -activestyle dotbox -background white -borderwidth 1 \
        -disabledforeground #a3a3a3 -exportselection 0 -font "TkFixedFont" \
        -foreground #000000 -height 572 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -justify left \
        -relief sunken -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -selectmode browse -setgrid 0 -state disabled \
        -width 144 
    $top.lis49 configure -font "TkFixedFont"
    $top.lis49 insert end text
    vTcl:DefineAlias "$top.lis49" "z21status" vTcl:WidgetProc "Toplevel1" 1
# add aa target = .top1.m51, basename = $top.m51
    menu "$top.m51" \
        -activebackground #d9d9d9 -activeborderwidth 1 \
        -activeforeground black -background #d9d9d9 -borderwidth 1 \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -relief raised -selectcolor #000000 -takefocus 0 -tearoff 0 \
        -type normal 
# add first menu widget
    labelframe "$top.lab50" \
        -borderwidth 2 -font "TkDefaultFont" -foreground #000000 \
        -labelanchor nw -relief groove -text "Lok 1" -background #d9d9d9 \
        -container 0 -height 155 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -padx 0 -pady 0 \
        -takefocus 0 -width 622 
    vTcl:DefineAlias "$top.lab50" "Lokframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab50
    canvas "$site_3_0.can53" \
        -background #d9d9d9 -borderwidth 2 -closeenough 1.0 -confine 1 \
        -height 61 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -insertbackground #000000 -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -offset 0,0 \
        -relief ridge -selectbackground #d9d9d9 -selectborderwidth 1 \
        -selectforeground black -state normal -width 161 -xscrollincrement 0 \
        -yscrollincrement 0 
    vTcl:DefineAlias "$site_3_0.can53" "Lokbild1" vTcl:WidgetProc "Toplevel1" 1
    scale "$site_3_0.sca54" \
        -activebackground #d9d9d9 -background #d9d9d9 -bigincrement 0.0 \
        -borderwidth 1 -digits 0 -font "TkDefaultFont" -foreground #000000 \
        -from 0.0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -length 564 -orient horizontal -relief flat \
        -repeatdelay 300 -repeatinterval 100 -resolution 1.0 -showvalue 1 \
        -sliderlength 30 -sliderrelief raised -state normal -tickinterval 0.0 \
        -to 100.0 -troughcolor #c4c4c4 -width 15 
    vTcl:DefineAlias "$site_3_0.sca54" "Lokscale1" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but55" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 1 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 29 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 3m -pady 1m \
        -relief raised -repeatdelay 0 -repeatinterval 0 -state normal \
        -text "Button" -underline -1 -width 25 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.but55" "Lokstop1" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but56" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 1 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 29 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 3m -pady 1m \
        -relief raised -repeatdelay 0 -repeatinterval 0 -state normal \
        -text "Button" -underline -1 -width 25 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.but56" "Lok_F1" vTcl:WidgetProc "Toplevel1" 1
# add p1 basename = $site_3_0.can53
    place $site_3_0.can53 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.267 -height 0 -relheight 0.4 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.sca54
    place $site_3_0.sca54 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.95 -height 0 -relheight 0.267 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.but55
    place $site_3_0.but55 \
        -in $site_3_0 -x 0 -relx 0.3 -y 0 -rely 0.2 -width 30 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.but56
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.367 -y 0 -rely 0.2 -width 30 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    ttk::panedwindow "$top.tPa49" \
        -orient horizontal -width 0 -height 0 -style "" 
    vTcl:DefineAlias "$top.tPa49" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tPa49.p1" \
        -labelanchor nw -text "Pane 1" -underline -1 -width 75 -height 200 \
        -style "" 
    vTcl:DefineAlias "$top.tPa49.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $top.tPa49.p1
    $top.tPa49 add $top.tPa49.p1 
    $top.tPa49 pane $top.tPa49.p1 -weight 0
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tPa49.p2" \
        -labelanchor nw -text "Pane 2" -underline -1 -width 125 -height 200 \
        -style "" 
    vTcl:DefineAlias "$top.tPa49.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_1 $top.tPa49.p2
    $top.tPa49 add $top.tPa49.p2 
    $top.tPa49 pane $top.tPa49.p2 -weight 0
$site_4_0 configure -width 75
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.lis49
    place $top.lis49 \
        -in $top -x 0 -relx 0.806 -y 0 -rely 0.008 -width 0 -relwidth 0.188 \
        -height 0 -relheight 0.983 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab50
    place $top.lab50 \
        -in $top -x 0 -relx 0.013 -y 0 -rely 0.017 -width 0 -relwidth 0.75 \
        -height 0 -relheight 0.25 -anchor nw -bordermode ignore 
# add p1 basename = $top.tPa49
    place $top.tPa49 \
        -in $top -x 0 -relx 0.006 -y 0 -rely 0.367 -width 0 -relwidth 0.775 \
        -height 0 -relheight 1.167 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

